# Generated by Django 3.2.6 on 2021-09-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_blogpost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
    ]
