# Generated by Django 3.2.6 on 2021-09-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210906_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name="person's first name"),
        ),
    ]
