# Generated by Django 3.2.6 on 2021-09-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210906_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='number',
            field=models.PositiveIntegerField(auto_created=True, default=0, unique=True),
        ),
    ]
