# Generated by Django 3.2.6 on 2021-09-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_main_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Main',
        ),
    ]
